### ISSUE TITLE
No fields including new targeting information

### ISSUE THREAD

**Issue by madshove-thy** [facebookresearch/Radlibrary#104]
Hi,

As this announcement mentions (https://www.facebook.com/business/news/transparency-social-issue-electoral-political-ads) new targeting information (or a summary) has been made available in the Ad Library. But, I can't seem to find any fields in 'Radlibrary' which allows me to get this information? Has this not been implemented in the package yet or do anyone more api-smart than me know how to do this?

Best,
Mads

**Comment by colin-fraser** [comment]
Hi Mads,

This new functionality is not currently available through the same API. There are no _current_ plans to implement any support for the Ad Library Report data into Radlibrary, but I'm looking into what might be possible. In the mean time, your best best for using this data is to use the Ad Library Report tool at https://www.facebook.com/ads/library/report and use the Download Report button at the bottom.
