### ISSUE TITLE
[Question] Continue aggregating to an existing paginated_adlib_data_response, if result_paginated$has_next is TRUE?

### ISSUE THREAD

**Issue by sysilviakim** [facebookresearch/Radlibrary#85]
Good evening,

Thank you for this great package---it is working fantastically. I was wondering if there was a way to continue aggregating to an existing `paginated_adlib_data_response` if `has_next` turned out to be `TRUE`. 

Suppose that I am doing a huge query and have no idea how many responses I'll get. I sure know that it will contain more than 1,000 responses, so I choose to use `adlib_get_paginated`. But I would not know what value to set to `max_gets`. Would my best bet be setting an unreasonably high number to it so that the internal `while` loop handles it? Something like

```
adlib_get_paginated(query, max_gets = 1e8, token = token)
```

I am wondering about a hypothetical situation where

* I think I set a good enough `max_gets`,
* but it turns out that `has_next` is still `TRUE`. 

I wonder what would be a good way to continue and not throw away the existing queried output. Before I started tinkering with a pull request, I wanted to see if there was something I am missing.

Thank you so much for your attention.

**Comment by colin-fraser** [comment]
I think you're right that this is a bit suboptimal at the moment, but I
don't think your proposed solution would break anything.

**Comment by sysilviakim** [comment]
Thank you! Sounds good. I'll stick to something like 1e16 just in case.

**Comment by colin-fraser** [comment]
Btw pull requests are more than welcome :)

**Comment by sysilviakim** [comment]
Of course. I am interested, but it will take some time. 

For the future audience, 1e16 gave me a 

> vector("list", max_gets) : vector size specified is too large

error and 1e10 gave me a cannot allocate a vector of 74GB error for my particular keyword.
