### ISSUE TITLE
Column names depreciated

### ISSUE THREAD

**Issue by blhills** [facebookresearch/Radlibrary#91]
i am getting the following error when using adlib_get()

response <- adlib_get(params = query, token = token)

Error in extract_error_message(response) : HTTP Error:
{
  "error": {
    "message": "(#12) ad_creative_body field is deprecated is deprecated for versions v13.0 and higher",
    "type": "OAuthException",
    "code": 12,
    "fbtrace_id": "AvIz2-8M2nWOYfaYBxfiZ7u"
  }
}

I assume it is because the column names have been updated as per https://developers.facebook.com/docs/graph-api/changelog/version13.0

ad_creative_body -> ad_creative_bodies
ad_creative_link_caption -> ad_creative_link_captions
ad_creative_link_description -> ad_creative_link_descriptions
ad_creative_link_title -> ad_creative_link_titles
funding_entity -> bylines
region_distribution -> delivery_by_region

I am not familiar with building/updating R packages (just using them :-) ) so thought I would mention it here.

**Comment by helenwieffering** [comment]
HI there, I'm experiencing this issue as well.

**Comment by colin-fraser** [comment]
hey friends, working on it :)

Thanks for bringing it up

**Comment by colin-fraser** [comment]
This should be fixed in this latest version! The API has changed a bit to reflect underlying changes in the way that data is now returned from the ad library API
